/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Common.EmailValidator;
import Entities.EndUser;
import java.awt.Color;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import Bus.*;

/**
 *
 * @author Administrator
 */
public class ForgotPassword extends javax.swing.JFrame {
 Account_Bus a = new Account_Bus();
    EndUser e = new EndUser();

   //Reup
    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
       setLocationRelativeTo(null);
       getContentPane().setBackground(new java.awt.Color(0,153,100));
        JRootPane rootPane = this.getRootPane();
        rootPane.setDefaultButton(btnRegister);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmailforget = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORGOT PASSWORD");

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1463602281_keepassx.png"))); // NOI18N
        btnRegister.setToolTipText("Get Password");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmail)
                .addGap(51, 51, 51)
                .addComponent(txtEmailforget, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmailforget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegister)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
      
                                                 
        // TODO add your handling code here:
        EmailValidator emailValidator = new EmailValidator();
        if (!emailValidator.validate(txtEmailforget.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Email Invalid!");
        } else {
            final String username = "hoavosac07101995@gmail.com";
            final String password = "Lecongthangandkutit07101995";
            Properties p = new Properties();
            p.put("mail.smtp.auth", "true");
            p.put("mail.smtp.starttls.enable", "true");
            p.put("mail.smtp.host", "smtp.gmail.com");
            p.put("mail.smtp.port", "587");
            Session s = Session.getInstance(p, new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(username, password);
                }
            });
            try {
                Message msg = new MimeMessage(s);
                msg.setFrom(new InternetAddress("hoavosac07101995@gmail.com"));
                msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(txtEmailforget.getText()));
                msg.setSubject("LogTime Software_Forgot Password");
                msg.setContent("<p>Your new password is: <h4 style=color:red;>m2tpjch</h4></p> <p>Please! Log in and change your password.</p> <p>Thank you!</p>", "text/html;");
                Transport.send(msg);
                //JOptionPane.showMessageDialog(null, "Done!");
                Forgot();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Fail! Please, check the network connection!");
            }
    }                                           
    }

    public boolean checkusernameagian(String username) {
        for (EndUser us : a.finllusername()) {
            if (us.getEmail().toUpperCase().equalsIgnoreCase(username.toUpperCase())) {
                return true;
            }
        }
        return false;
    }

    void Forgot() {
        try {

            String email = this.txtEmailforget.getText();

            String password = "m2tpjch";

            if (email.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Email is empty");
            } else if (!email.isEmpty() && !password.isEmpty()) {

                if (!checkusernameagian(email)) {
                    JOptionPane.showMessageDialog(null, "Email don't exists");
                } else {
                    e.setEmail(email);
                    e.setPass(password);
                    if (a.update(e)) {
                        JOptionPane.showMessageDialog(null, "Successfully! Please check email to get password");
                        JFrameMain f = new JFrameMain(txtEmailforget.getText());
                        f.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Failure! Please try again.");

                    }
                }
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    
    }//GEN-LAST:event_btnRegisterActionPerformed
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JTextField txtEmailforget;
    // End of variables declaration//GEN-END:variables
}
