/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Entities.*;
import Bus.*;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class JFrameTags extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFrameTags
     */
    Tags t = new Tags();
    Tags_Bus tb = new Tags_Bus();
    Account_Bus a = new Account_Bus();

    public JFrameTags() {
        super("MANAGE TAGS", false, false, false, false);
        initComponents();
        ImageIcon titleIcon = new ImageIcon("src\\Images\\1463614449_tag.png");
        this.setFrameIcon(titleIcon);
        LoadData();
    }

    private void LoadData() {
        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("ID");
        dt.addColumn("Tag Name");
        dt.addColumn("Description");
        for (Tags t : tb.findall(LogTimeMain.Username)) {
            dt.addRow(new Object[]{t.getId(), t.getTagName(), t.getDescription()});

        }
        this.tblTags.setModel(dt);
        this.tblTags.repaint();
        this.tblTags.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTags = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTagName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDes = new javax.swing.JTextArea();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setClosable(true);
        setTitle("MANAGE TAGS");
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(777, 432));

        tblTags.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTags.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTagsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTags);

        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1462374937_Plus.png"))); // NOI18N
        btnInsert.setToolTipText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1462374983_system-software-update.png"))); // NOI18N
        btnUpdate.setToolTipText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1462375022_Close_Box_Red.png"))); // NOI18N
        btnDelete.setToolTipText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Tag Name:");

        jLabel2.setText("Description:");

        txtDes.setColumns(20);
        txtDes.setRows(5);
        jScrollPane2.setViewportView(txtDes);

        txtSearch.setToolTipText("Input key search and press \"Enter\"");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        jLabel3.setText("Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTagName))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(62, 62, 62)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(65, 65, 65)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, Short.MAX_VALUE))
                                .addComponent(jScrollPane2)
                                .addComponent(txtSearch))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTagName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
        String tagName = txtTagName.getText();
        String Des = txtDes.getText();
        int ID = Integer.parseInt(tblTags.getValueAt(tblTags.getSelectedRow(), 0).toString());
        if (tagName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tag name is empty");
        } else {

            t.setTagName(tagName);
            t.setDescription(Des);
            t.setId(ID);
            if (tb.Update(t)) {
                LoadData();
                ClearText();
            } else {
                JOptionPane.showMessageDialog(null, "Update tag failure");

            }
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Tags is not selected!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
    void ClearText() {
        txtTagName.setText("");
        txtDes.setText("");
    }

    public boolean checktag(String name) {
        for (Tags us : tb.findall(LogTimeMain.Username)) {
            if (us.getTagName().toUpperCase().equalsIgnoreCase(name.toUpperCase())) {
                return true;
            }
        }
        return false;
    }
    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String tagName = txtTagName.getText();
        String Des = txtDes.getText();
        String Email = LogTimeMain.Username;
        boolean status = true;
        //JOptionPane.showMessageDialog(null, id_user);
        if (tagName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tag name is empty");
        } else if (checktag(tagName)) {
            JOptionPane.showMessageDialog(null, "Tag name already exist");
        } else {

            t.setTagName(tagName);
            t.setDescription(Des);
            t.setStatus(status);
            t.setEndUser(Email);
            if (tb.Create(t)) {
                LoadData();
                ClearText();
            } else {
                JOptionPane.showMessageDialog(null, "Add Tag failure");

            }
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int ID = Integer.parseInt(tblTags.getValueAt(tblTags.getSelectedRow(), 0).toString());
            int reply = JOptionPane.showConfirmDialog(null, "Do you really want delete?", "Notice!", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                tb.delete(ID);
                LoadData();
                ClearText();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tags is not selected");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblTagsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTagsMouseClicked
        // TODO add your handling code here:
        int ID = Integer.parseInt(tblTags.getValueAt(tblTags.getSelectedRow(), 0).toString());
        Tags t = tb.find(ID);
        if (t != null) {
            txtTagName.setText(t.getTagName().toString());
            txtDes.setText(t.getDescription().toString());
        }
    }//GEN-LAST:event_tblTagsMouseClicked

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            search();
        } else if (txtSearch.getText().isEmpty()) {
            LoadData();
        }
    }//GEN-LAST:event_txtSearchKeyPressed
    public void search() {
        DefaultTableModel dtm = (DefaultTableModel) this.tblTags.getModel();
        dtm.fireTableDataChanged();
        TableRowSorter sorter = new TableRowSorter(dtm);
        this.tblTags.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + this.txtSearch.getText()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTags;
    private javax.swing.JTextArea txtDes;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTagName;
    // End of variables declaration//GEN-END:variables
}
